{% set version = "5.7" %}

package:
  name: pyqt
  version: {{ version }}

source:
  fn: PyQt5_gpl-{{ version }}.tar.gz  # [osx and linux]
  url: https://sourceforge.net/projects/pyqt/files/PyQt5/PyQt-{{ version }}/PyQt5_gpl-{{ version }}.tar.gz  # [osx and linux]
  sha256: 892693ba5f79989abb2061dad2d5c4e6f127e9dd3240f73f8220c7152cd35b05  # [osx and linux]
  fn: PyQt5_gpl-{{ version }}.zip  # [win]
  url: https://sourceforge.net/projects/pyqt/files/PyQt5/PyQt-{{ version }}/PyQt5_gpl-{{ version }}.zip  # [win]
  sha256: 1607a90af2c2e944e2aebc7ba4a7ec9c327ec78afbaf3a5eab2b6c65cd81d1e5  # [win]

build:
  number: 0
  skip: true  # [not py35]

requirements:
  build:
    - python
    - icu ==56.1
  run:
    - python
    - icu ==56.1

test:
  imports:
    - PyQt5.QtCore
    - PyQt5.QtGui
  commands:
    - pyuic5 --version
    - pyrcc5 --version
    - pylupdate5 -help

about:
  home: http://www.riverbankcomputing.co.uk/software/pyqt
  license: Commercial, GPLv2, GPLv3
  license_family: GPL3
  summary: Python binding of the cross-platform GUI toolkit Qt
  description: |
    PyQt is a set of Python v2 and v3 bindings for The Qt Company's Qt
    application framework and runs on all platforms supported by Qt including
    Windows, MacOS/X and Linux. PyQt5 supports Qt v5. PyQt4 supports Qt v4 and
    will build against Qt v5. The bindings are implemented as a set of Python
    modules and contain over 1,000 classes.
  doc_url: https://www.riverbankcomputing.com/software/pyqt/

extra:
  recipe-maintainers:
    - ccordoba12
    - mingwandroid
    - gillins
    - msarahan
    - ocefpaf
    - hadim
