{% set version = "6.11.0" %}
{% set sip_version = "6.15.3" %}
{% set pyqt6_sip_version = "13.10.0" %}
{% set webengine_version = "6.8.0" %}
{% set charts_version = "6.8.0" %}
{% set pyqt_builder_version = "1.18.2" %}


package:
  name: pyqt6-split
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/P/PyQt{{ version[0] }}/pyqt{{ version[0] }}-{{ version }}.tar.gz
    sha256: 45dd60aa69976de1918b5ced6b4e7b6a25abd2a919ecef5fd5826ecc76718889
    folder: pyqt

  - url: https://pypi.org/packages/source/P/PyQt6-sip/pyqt6_sip-{{ pyqt6_sip_version }}.tar.gz
    sha256: d6daa95a0bd315d9ec523b549e0ce97455f61ded65d5eafecd83ed2aa4ae5350
    folder: pyqt_sip

  - url: https://pypi.org/packages/source/P/PyQt6-WebEngine/PyQt6_WebEngine-{{ webengine_version }}.tar.gz
    sha256: 64045ea622b6a41882c2b18f55ae9714b8660acff06a54e910eb72822c2f3ff2
    folder: pyqt_webengine

  - url: https://pypi.org/packages/source/P/PyQt6-Charts/PyQt6_Charts-{{ charts_version }}.tar.gz
    sha256: f86705b8740e3041667ce211aeaa205b750eb6baf4c908f4e3f6dc8c720d10f1
    folder: pyqt_charts

build:
  number: 0
  skip:
    - true  # [linux and aarch64]
    - true  # [linux and ppc64le]

outputs:
  - name: pyqt6-sip
    version: {{ pyqt6_sip_version }}
    script: build-pyqt-sip.sh  # [not win]
    script: bld-pyqt-sip.bat  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - python
        - setuptools
        - wheel
        - pip
        - setuptools
      run:
        - python
        - sip
        - packaging
        - toml
    test:
      imports:
        - PyQt6.sip

  - name: pyqt6
    version: {{ version }}
    script: build-pyqt.sh  # [not win]
    script: bld-pyqt.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage('pyqt6', max_pin='x.x') }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
        - jom                                      # [win]
        - python                                   # [build_platform != target_platform]
        - cross-python_{{ target_platform }}       # [build_platform != target_platform]
        - pyqt-builder {{ pyqt_builder_version }}  # [build_platform != target_platform]
        - sip {{ sip_version }}                    # [build_platform != target_platform]
        - qt6-main {{ version }}                   # [build_platform != target_platform]
        - make
      host:
        - python
        - pip
        - setuptools
        - sip {{ sip_version }}                    # [build_platform == target_platform]
        - toml
        - pyqt-builder {{ pyqt_builder_version }}  # [build_platform == target_platform]
        - packaging
        - qt6-main {{ version }}
        - libgl-devel                            # [linux]
        - libegl-devel                           # [linux]
        - libopengl-devel                        # [linux]
        - xorg-xorgproto                         # [linux]
        - xcb-util                               # [linux]
        - xcb-util-wm                            # [linux]
        - xcb-util-keysyms                       # [linux]
        - xcb-util-image                         # [linux]
        - xcb-util-renderutil                    # [linux]
        - xorg-libx11                            # [linux]
        - xorg-libxext                           # [linux]
        - xorg-libxdamage                        # [linux]
        - xorg-libsm                             # [linux]
        - xorg-libice                            # [linux]
        - xorg-libxcomposite                     # [linux]
        - xorg-libxxf86vm                        # [linux]
        - xorg-xf86vidmodeproto                  # [linux]
      run:
        - python
        - {{ pin_subpackage('pyqt6-sip', exact=True) }}
    test:
      files:
        - pyqt_test.py
      imports:
        - PyQt6
        - PyQt6.sip
        - PyQt6.QtCore
        - PyQt6.QtGui
        - PyQt6.QtHelp
        - PyQt6.QtNetwork
        - PyQt6.QtOpenGL
        - PyQt6.QtPrintSupport
        - PyQt6.QtQml
        - PyQt6.QtQuick
        - PyQt6.QtQuickWidgets
        - PyQt6.QtSvg
        - PyQt6.QtSvgWidgets
        - PyQt6.QtTest
        - PyQt6.QtWebChannel
        - PyQt6.QtWebSockets
        - PyQt6.QtWidgets
        - PyQt6.QtXml
      commands:
        - DISPLAY=localhost:1.0 xvfb-run -a bash -c 'python pyqt_test.py'  # [linux and build_platform == target_platform]
        - pyuic6 --version  # [not win]

  - name: pyqt6webengine
    version: {{ version }}
    script: build-pyqtwebengine.sh  # [not win]
    script: bld-pyqtwebengine.bat  # [win]
    build:
      skip: true # https://github.com/conda-forge/pyqt-feedstock/issues/156
      run_exports:
        - {{ pin_subpackage('pyqt6webengine', max_pin='x.x') }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
        - jom                                      # [win]
        - python                                   # [build_platform != target_platform]
        - cross-python_{{ target_platform }}       # [build_platform != target_platform]
        - pyqt-builder {{ pyqt_builder_version }}  # [build_platform != target_platform]
        - sip {{ sip_version }}                    # [build_platform != target_platform]
        - qt6-main {{ version }}                   # [build_platform != target_platform]
        - make
      host:
        - python
        - pip
        - setuptools
        - sip {{ sip_version }}                    # [build_platform == target_platform]
        - toml
        - pyqt-builder {{ pyqt_builder_version }}  # [build_platform == target_platform]
        - packaging
        - pyqt6
        - qt6-main {{ version }}
        - qt6-webengine {{ version }}            # [build_platform != target_platform]
        - libgl-devel                            # [linux]
        - libegl-devel                           # [linux]
        - libopengl-devel                        # [linux]
        - xorg-xorgproto                         # [linux]
        - xcb-util                               # [linux]
        - xcb-util-wm                            # [linux]
        - xcb-util-keysyms                       # [linux]
        - xcb-util-image                         # [linux]
        - xcb-util-renderutil                    # [linux]
        - xorg-libx11                            # [linux]
        - xorg-libxext                           # [linux]
        - xorg-libxdamage                        # [linux]
        - xorg-libsm                             # [linux]
        - xorg-libice                            # [linux]
        - xorg-libxcomposite                     # [linux]
        - xorg-libxxf86vm                        # [linux]
        - xorg-xf86vidmodeproto                  # [linux]
      run:
        - python
        - {{ pin_subpackage('pyqt6', max_pin='x.x') }}
    test:
      imports:
        - PyQt6.QtWebEngine
        - PyQt6.QtWebEngineCore
        - PyQt6.QtWebEngineWidgets

  - name: pyqt6-charts
    version: {{ version }}
    script: build-pyqtcharts.sh  # [not win]
    script: bld-pyqtcharts.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage('pyqt6-charts', max_pin='x.x') }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
        - jom                                      # [win]
        - python                                   # [build_platform != target_platform]
        - cross-python_{{ target_platform }}       # [build_platform != target_platform]
        - pyqt-builder {{ pyqt_builder_version }}  # [build_platform != target_platform]
        - sip {{ sip_version }}                    # [build_platform != target_platform]
        - qt6-main {{ version }}                   # [build_platform != target_platform]
        - qt6-charts {{ version }}                 # [build_platform != target_platform]
        - make
      host:
        - python
        - pip
        - setuptools
        - sip {{ sip_version }}                    # [build_platform == target_platform]
        - toml
        - pyqt-builder {{ pyqt_builder_version }}  # [build_platform == target_platform]
        - packaging
        - qt6-main {{ version }}
        - qt6-charts {{ version }}
        - pyqt6
        - libgl-devel                            # [linux]
        - libegl-devel                           # [linux]
        - libopengl-devel                        # [linux]
        - xorg-xorgproto                         # [linux]
        - xcb-util                               # [linux]
        - xcb-util-wm                            # [linux]
        - xcb-util-keysyms                       # [linux]
        - xcb-util-image                         # [linux]
        - xcb-util-renderutil                    # [linux]
        - xorg-libx11                            # [linux]
        - xorg-libxext                           # [linux]
        - xorg-libxdamage                        # [linux]
        - xorg-libsm                             # [linux]
        - xorg-libice                            # [linux]
        - xorg-libxcomposite                     # [linux]
        - xorg-libxxf86vm                        # [linux]
        - xorg-xf86vidmodeproto                  # [linux]
      run:
        - python
        - {{ pin_subpackage('pyqt6', max_pin='x.x') }}
    test:
      imports:
        - PyQt6.QtCharts

about:
  home: https://www.riverbankcomputing.com/software/pyqt/
  license: GPL-3.0-only
  license_family: GPL
  license_file: pyqt/LICENSE
  summary: Python bindings for the Qt cross platform application toolkit
  # The remaining entries in this section are optional, but recommended.
  description: |
    PyQt5 is a comprehensive set of Python bindings for Qt v5.
    It is implemented as more than 35 extension modules and enables Python
    to be used as an alternative application development language to C++ on
    all supported platforms including iOS and Android.
  doc_url: https://www.riverbankcomputing.com/static/Docs/PyQt5/
  dev_url: https://www.riverbankcomputing.com/mailman/listinfo/pyqt/

extra:
  recipe-maintainers:
    - andfoy
    - ccordoba12
    - mingwandroid
    - gillins
    - msarahan
    - ocefpaf
    - jschueller
  feedstock-name: pyqt
