{% set version = "5.12.3" %}

package:
  name: pyqt_split
  version: {{ version }}

source:
  - url: https://distfiles.macports.org/py-pyqt5/PyQt5_gpl-{{ version }}.tar.gz
    sha1: f442a876794947a24474cf85eb02abd60f00f642
    patches:
      - 0003-configure.patch
      # remove build path from .bat
      - 0004-configure-winbat.patch  # [win]
      - py2_segfault.diff
      - qt5_dll.diff
    folder: pyqt5

  - url: https://distfiles.macports.org/py-sip/sip-4.19.18.tar.gz
    sha1: d001eb00f6dae26a952770e805b1519f61cae77d
    patches:
      - 0001-Do-not-override-CC-CXX-LINK-in-sipgen-Makefile.patch
      # AttributeError: module 'distutils.sysconfig' has no attribute 'get_config_h_filename'
      - sip-get_config_h_filename.patch
    folder: sip

  - url: https://distfiles.macports.org/py-pyqt5/PyQtWebEngine_gpl-5.12.1.tar.gz
    sha1: 737acf93ecf39e5e2136e094a8b0a9ffa47bd2de
    folder: pyqtwebengine

  - url: https://github.com/ocefpaf/pyqt-feedstock/releases/download/v5.12.3/PyQtChart_gpl-5.12.tar.gz
    sha1: 6a876ac37d0ccb5392f67669de5e790c8f9188da
    folder: pyqtcharts

build:
  number: 7
  skip: true  # [win and py27]
  skip: true  # [ppc64le]

outputs:
  - name: pyqt5-sip
    version: 4.19.18
    script: build-pyqt-sip.sh   # [not win]
    script: bld-pyqt-sip.bat  # [win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ compiler('c') }}
        - make  # [not win]
      host:
        - python
      run:
        - python
    test:
      imports:
        - PyQt5.sip

  - name: pyqt-impl
    script: build-pyqt.sh   # [not win]
    script: bld-pyqt.bat  # [win]
    requirements:
      run_constrained:                                            # [osx]
        - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx]
      build:
        # We may want to find and add a Python dbus library?
        # pkg-config --cflags-only-I --libs dbus-1
        # The Python dbus module doesn't seem to be installed.
        - {{ compiler('cxx') }}
        - {{ compiler('c') }}
        - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
        - {{ cdt('libx11-devel') }}          # [linux]
        - {{ cdt('libxcb') }}                # [linux]
        - {{ cdt('libxext-devel') }}         # [linux]
        - {{ cdt('libxrender-devel') }}      # [linux]
        - {{ cdt('mesa-libgl-devel') }}      # [linux]
        - {{ cdt('mesa-libegl-devel') }}     # [linux]
        - {{ cdt('mesa-dri-drivers') }}      # [linux]
        - {{ cdt('libxau-devel') }}          # [linux]
        - {{ cdt('alsa-lib-devel') }}        # [linux]
        - {{ cdt('gtk2-devel') }}            # [linux]
        - {{ cdt('gtkmm24-devel') }}         # [linux]
        - {{ cdt('libdrm-devel') }}          # [linux]
        - {{ cdt('libxcomposite-devel') }}   # [linux]
        - {{ cdt('libxcursor-devel') }}      # [linux]
        - {{ cdt('libxi-devel') }}           # [linux]
        - {{ cdt('libxrandr-devel') }}       # [linux]
        - {{ cdt('pciutils-devel') }}        # [linux]
        - {{ cdt('libxscrnsaver-devel') }}   # [linux]
        - {{ cdt('libxtst-devel') }}         # [linux]
        - {{ cdt('libselinux-devel') }}      # [linux]
        - {{ cdt('libxdamage') }}            # [linux]
        - {{ cdt('libxfixes') }}             # [linux]
        - {{ cdt('libxxf86vm') }}            # [linux]
        - {{ cdt('mesa-libgbm') }}           # [linux]
        - jom  # [win]
        - pkg-config  # [not win]
      host:
        - {{ cdt('mesa-libgl-devel') }}      # [linux]
        - python
        - dbus  # [not win]
        - qt 5.12.*
        - enum34  # [py27]
        - {{ pin_subpackage('pyqt5-sip', exact=True) }}
      run:
        - python
        - {{ pin_compatible("qt", max_pin="x.x") }}
        - enum34  # [py27]
        - {{ pin_subpackage('pyqt5-sip', exact=True) }}
    test:
      files:
        - pyqt_test.py
      imports:
        - PyQt5.sip
        - PyQt5.QtCore
        - PyQt5.QtGui
        - PyQt5.QtHelp
        - PyQt5.QtMultimedia
        - PyQt5.QtMultimediaWidgets
        - PyQt5.QtNetwork
        - PyQt5.QtOpenGL
        - PyQt5.QtPrintSupport
        - PyQt5.QtQml
        - PyQt5.QtQuick
        - PyQt5.QtSvg
        - PyQt5.QtTest
        - PyQt5.QtWebChannel
        - PyQt5.QtWebSockets
        - PyQt5.QtWidgets
        - PyQt5.QtXml
        - PyQt5.QtXmlPatterns
      commands:
        - DISPLAY=localhost:1.0 xvfb-run -a bash -c 'python pyqt_test.py'  # [linux]
        - pyuic5 --version  # [not win]

  - name: pyqtwebengine
    version: 5.12.1
    script: build-pyqtwebengine.sh   # [not win]
    script: bld-pyqtwebengine.bat  # [win]
    requirements:
      run_constrained:                                            # [osx]
        - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx]
      build:
        # We may want to find and add a Python dbus library?
        # pkg-config --cflags-only-I --libs dbus-1
        # The Python dbus module doesn't seem to be installed.
        - {{ compiler('cxx') }}
        - {{ compiler('c') }}
        - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
        - {{ cdt('libx11-devel') }}          # [linux]
        - {{ cdt('libxcb') }}                # [linux]
        - {{ cdt('libxext-devel') }}         # [linux]
        - {{ cdt('libxrender-devel') }}      # [linux]
        - {{ cdt('mesa-libgl-devel') }}      # [linux]
        - {{ cdt('mesa-libegl-devel') }}     # [linux]
        - {{ cdt('mesa-dri-drivers') }}      # [linux]
        - {{ cdt('libxau-devel') }}          # [linux]
        - {{ cdt('alsa-lib-devel') }}        # [linux]
        - {{ cdt('gtk2-devel') }}            # [linux]
        - {{ cdt('gtkmm24-devel') }}         # [linux]
        - {{ cdt('libdrm-devel') }}          # [linux]
        - {{ cdt('libxcomposite-devel') }}   # [linux]
        - {{ cdt('libxcursor-devel') }}      # [linux]
        - {{ cdt('libxi-devel') }}           # [linux]
        - {{ cdt('libxrandr-devel') }}       # [linux]
        - {{ cdt('pciutils-devel') }}        # [linux]
        - {{ cdt('libxscrnsaver-devel') }}   # [linux]
        - {{ cdt('libxtst-devel') }}         # [linux]
        - {{ cdt('libselinux-devel') }}      # [linux]
        - {{ cdt('libxdamage') }}            # [linux]
        - {{ cdt('libxfixes') }}             # [linux]
        - {{ cdt('libxxf86vm') }}            # [linux]
        - {{ cdt('mesa-libgbm') }}           # [linux]
        - jom  # [win]
        - pkg-config  # [not win]
      host:
        - {{ cdt('mesa-libgl-devel') }}      # [linux]
        - python
        - dbus  # [not win]
        - qt 5.12.*
        - enum34  # [py27]
        - {{ pin_subpackage('pyqt-impl', exact=True) }}
      run:
        - python
        - {{ pin_compatible("qt", max_pin="x.x") }}
        - enum34  # [py27]
        - {{ pin_subpackage('pyqt-impl', exact=True) }}
    test:
      imports:
        - PyQt5.QtWebEngine
        - PyQt5.QtWebEngineCore
        - PyQt5.QtWebEngineWidgets

  - name: pyqtchart
    version: "5.12"
    script: build-pyqtcharts.sh   # [not win]
    script: bld-pyqtcharts.bat  # [win]
    requirements:
      run_constrained:                                            # [osx]
        - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx]
      build:
        # We may want to find and add a Python dbus library?
        # pkg-config --cflags-only-I --libs dbus-1
        # The Python dbus module doesn't seem to be installed.
        - {{ compiler('cxx') }}
        - {{ compiler('c') }}
        - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
        - {{ cdt('libx11-devel') }}          # [linux]
        - {{ cdt('libxcb') }}                # [linux]
        - {{ cdt('libxext-devel') }}         # [linux]
        - {{ cdt('libxrender-devel') }}      # [linux]
        - {{ cdt('mesa-libgl-devel') }}      # [linux]
        - {{ cdt('mesa-libegl-devel') }}     # [linux]
        - {{ cdt('mesa-dri-drivers') }}      # [linux]
        - {{ cdt('libxau-devel') }}          # [linux]
        - {{ cdt('alsa-lib-devel') }}        # [linux]
        - {{ cdt('gtk2-devel') }}            # [linux]
        - {{ cdt('gtkmm24-devel') }}         # [linux]
        - {{ cdt('libdrm-devel') }}          # [linux]
        - {{ cdt('libxcomposite-devel') }}   # [linux]
        - {{ cdt('libxcursor-devel') }}      # [linux]
        - {{ cdt('libxi-devel') }}           # [linux]
        - {{ cdt('libxrandr-devel') }}       # [linux]
        - {{ cdt('pciutils-devel') }}        # [linux]
        - {{ cdt('libxscrnsaver-devel') }}   # [linux]
        - {{ cdt('libxtst-devel') }}         # [linux]
        - {{ cdt('libselinux-devel') }}      # [linux]
        - {{ cdt('libxdamage') }}            # [linux]
        - {{ cdt('libxfixes') }}             # [linux]
        - {{ cdt('libxxf86vm') }}            # [linux]
        - {{ cdt('mesa-libgbm') }}           # [linux]
        - jom  # [win]
        - pkg-config  # [not win]
      host:
        - {{ cdt('mesa-libgl-devel') }}      # [linux]
        - python
        - dbus  # [not win]
        - qt 5.12.*
        - enum34  # [py27]
        - {{ pin_subpackage('pyqt-impl', exact=True) }}
      run:
        - python
        - {{ pin_compatible("qt", max_pin="x.x") }}
        - enum34  # [py27]
        - {{ pin_subpackage('pyqt-impl', exact=True) }}
    test:
      imports:
        - PyQt5.QtChart

  - name: pyqt
    build:
      run_exports:
        - {{ pin_subpackage('pyqt', max_pin='x.x') }}
    requirements:
      run_constrained:                                            # [osx]
        - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx]
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('pyqt5-sip', exact=True) }}
        - {{ pin_subpackage('pyqt-impl', exact=True) }}
        - {{ pin_subpackage('pyqtwebengine', exact=True) }}
        - {{ pin_subpackage('pyqtchart', exact=True) }}
    test:
      files:
        - pyqt_test.py
      imports:
        - PyQt5.sip
        - PyQt5.QtChart
        - PyQt5.QtCore
        - PyQt5.QtGui
        - PyQt5.QtHelp
        - PyQt5.QtMultimedia
        - PyQt5.QtMultimediaWidgets
        - PyQt5.QtNetwork
        - PyQt5.QtOpenGL
        - PyQt5.QtPrintSupport
        - PyQt5.QtQml
        - PyQt5.QtQuick
        - PyQt5.QtSvg
        - PyQt5.QtTest
        - PyQt5.QtWebChannel
        - PyQt5.QtWebEngine
        - PyQt5.QtWebEngineCore
        - PyQt5.QtWebEngineWidgets
        - PyQt5.QtWebSockets
        - PyQt5.QtWidgets
        - PyQt5.QtXml
        - PyQt5.QtXmlPatterns
      commands:
        - DISPLAY=localhost:1.0 xvfb-run -a bash -c 'python pyqt_test.py'  # [linux]
        - pyuic5 --version  # [not win]
        - conda list  # [not win]

about:
  home: http://www.riverbankcomputing.co.uk/software/pyqt
  license: LicenseRef-Commercial or GPL-2.0-only or GPL-3.0-only
  license_family: GPL
  license_file: pyqt5/LICENSE
  summary: 'Python binding of the cross-platform GUI toolkit Qt.'
  description: |
    "PyQt is a set of Python v2 and v3 bindings for The Qt Company's Qt
    application framework and runs on all platforms supported by Qt including
    Windows, MacOS/X and Linux. PyQt5 supports Qt v5. PyQt4 supports Qt v4 and
    will build against Qt v5. The bindings are implemented as a set of Python
    modules and contain over 1,000 classes."
  doc_url: https://www.riverbankcomputing.com/software/pyqt/
  dev_url: https://github.com/pyqt

extra:
  recipe-maintainers:
    - ccordoba12
    - mingwandroid
    - gillins
    - msarahan
    - ocefpaf
    - jschueller
