{% set pyqt_name = "PyQt6" %}
{% set pyqt_builder_name = "PyQt-builder" %}
{% set pyqt_sip_name = "PyQt6-sip" %}
{% set version = "6.8.1" %}
{% set sip_version = "13.10.0" %}
{% set pyqt_builder_version = "1.15.4" %}
{% set webengine_name = "PyQtWebEngine" %}
{% set webengine_version = "6.8.1" %}
{% set charts_name = "PyQt6-Charts" %}
{% set charts_version = "6.8.0" %}
{% set PYTHON = PYTHON | default("$PYTHON") %}
{% set python_min = python_min | default("3.6") %}


package:
  name: pyqt6-split
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ pyqt_builder_name[0] }}/{{ pyqt_builder_name }}/{{ pyqt_builder_name }}-{{ pyqt_builder_version }}.tar.gz
    sha256: 39f8c75db17d9ce17cb6bbf3df1650b5cebc1ea4e5bd73843d21cc96612b2ae1
    folder: pyqt-builder
    patches:
      #- patches/0001-Use-conda-sysroot-when-building-recipes.patch
      - patches/0002-disable-test-execution-cross.patch
      - patches/0003-find-sip-distinfo.patch
      - patches/0004-Use-conda-sysroot-when-building-recipes.patch

  - url: https://pypi.org/packages/source/{{ pyqt_name[0] }}/{{ pyqt_name }}/{{ pyqt_name.replace('-', '_').lower() }}-{{ version }}.tar.gz
    sha256: 91d937d6166274fafd70f4dee11a8da6dbfdb0da53de05f5d62361ddf775e256
    folder: pyqt

  - url: https://pypi.org/packages/source/{{ pyqt_sip_name[0] }}/{{ pyqt_sip_name }}/{{ pyqt_sip_name.replace('-', '_').lower() }}-{{ sip_version }}.tar.gz
    sha256: d6daa95a0bd315d9ec523b549e0ce97455f61ded65d5eafecd83ed2aa4ae5350
    folder: pyqt_sip

  # - url: https://pypi.org/packages/source/{{ webengine_name[0] }}/{{ webengine_name }}/{{ webengine_name }}-{{ webengine_version }}.tar.gz
  #   sha256: cedc28f54165f4b8067652145aec7f732a17eadf6736835852868cf76119cc19
  #   folder: pyqt_webengine

  - url: https://pypi.org/packages/source/{{ charts_name[0] }}/{{ charts_name }}/{{ charts_name.replace('-', '_') }}-{{ charts_version }}.tar.gz
    sha256: f86705b8740e3041667ce211aeaa205b750eb6baf4c908f4e3f6dc8c720d10f1
    folder: pyqt_charts

build:
  number: 0

outputs:
  # Not actually exporting this package, just experimenting to see if
  # this needs to be patched.
  - name: my-pyqt6-builder
    version: {{ pyqt_builder_version }}
    build:
      noarch: python
      script: cd pyqt-builder && {{ PYTHON }} -m pip install . -vv
      entry_points:
        - pyqt-bundle = pyqtbuild.bundle.bundle_main:main
        - pyqt-qt-wheel = pyqtbuild.bundle.qt_wheel_main:main

    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - python
        - setuptools
        - wheel
        - pip
      run:
        - python
        - sip
        - packaging
        - toml

  - name: pyqt6-sip
    version: {{ sip_version }}
    script: build-pyqt-sip.sh  # [not win]
    script: bld-pyqt-sip.bat  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - python
        - setuptools
        - wheel
        - pip
      run:
        - python
        - sip
        - packaging
        - toml
    test:
      imports:
        - PyQt6.sip

  - name: pyqt6
    version: {{ version }}
    script: build-pyqt.sh  # [not win]
    script: bld-pyqt.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage('pyqt6', max_pin='x.x') }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib('c') }}
        - {{ compiler('cxx') }}
        - jom                                # [win]
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        #- pyqt-builder                          # [build_platform != target_platform]
        - my-pyqt6-builder                       # [build_platform != target_platform]
        - sip                                    # [build_platform != target_platform]
        - qt6-main {{ version }}                 # [build_platform != target_platform]
        - make
      host:
        - python
        - pip
        - sip                                    # [build_platform == target_platform]
        - toml
        #- pyqt-builder                          # [build_platform == target_platform]
        - my-pyqt6-builder                       # [build_platform == target_platform]
        - packaging
        - qt6-main {{ version }}
        - libgl-devel                            # [linux]
        - libegl-devel                           # [linux]
        - libopengl-devel                        # [linux]
        - libdrm                                 # [linux]
      run:
        - python
        - {{ pin_subpackage('pyqt6-sip', exact=True) }}
    test:
      files:
        - pyqt_test.py
      imports:
        - PyQt6
        - PyQt6.sip
        - PyQt6.QtCore
        - PyQt6.QtGui
        - PyQt6.QtHelp
        # - PyQt6.QtMultimedia # Made add-on in Qt6?
        # - PyQt6.QtMultimediaWidgets # Made add-on in Qt6?
        - PyQt6.QtNetwork
        - PyQt6.QtOpenGL
        - PyQt6.QtOpenGLWidgets # New in Qt6?
        - PyQt6.QtPrintSupport
        - PyQt6.QtQml
        - PyQt6.QtQuick
        - PyQt6.QtQuickWidgets # New in Qt6?
        - PyQt6.QtSvg
        - PyQt6.QtSvgWidgets # New in Qt6?
        - PyQt6.QtTest
        - PyQt6.QtWebChannel
        - PyQt6.QtWebSockets
        - PyQt6.QtWidgets
        - PyQt6.QtXml
      commands:
        # xvfb-run not found.
        # - DISPLAY=localhost:1.0 xvfb-run -a bash -c 'python pyqt_test.py'  # [linux and build_platform == target_platform]
        - pyuic6 --version  # [not win]

  # - name: pyqt6webengine
  #   version: {{ version }}
  #   script: build-pyqtwebengine.sh  # [not win]
  #   script: bld-pyqtwebengine.bat  # [win]
  #   build:
  #     run_exports:
  #       - {{ pin_subpackage('pyqt6webengine', max_pin='x.x') }}
  #   requirements:
  #     run_constrained:   # [osx and x86_64]
  #       - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.14") }}  # [osx and x86_64]
  #     build:
  #       - {{ compiler('c') }}
  #       - {{ compiler('cxx') }}
  #       - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
  #       - {{ cdt('libx11-devel') }}          # [linux]
  #       - {{ cdt('libxext') }}               # [linux]
  #       - {{ cdt('libxext-devel') }}         # [linux]
  #       - {{ cdt('libxrender-devel') }}      # [linux]
  #       - {{ cdt('mesa-libgl-devel') }}      # [linux]
  #       - {{ cdt('mesa-libegl') }}           # [linux]
  #       - {{ cdt('mesa-libegl-devel') }}     # [linux]
  #       - {{ cdt('mesa-dri-drivers') }}      # [linux]
  #       - {{ cdt('libxau-devel') }}          # [linux]
  #       - {{ cdt('alsa-lib-devel') }}        # [linux]
  #       - {{ cdt('gtk2-devel') }}            # [linux]
  #       - {{ cdt('gtkmm24-devel') }}         # [linux]
  #       - {{ cdt('libdrm-devel') }}          # [linux]
  #       - {{ cdt('libxcomposite-devel') }}   # [linux]
  #       - {{ cdt('libxcursor-devel') }}      # [linux]
  #       - {{ cdt('libxi-devel') }}           # [linux]
  #       - {{ cdt('libxrandr-devel') }}       # [linux]
  #       - {{ cdt('pciutils-devel') }}        # [linux]
  #       - {{ cdt('libxscrnsaver-devel') }}   # [linux]
  #       - {{ cdt('libxtst-devel') }}         # [linux]
  #       - {{ cdt('libselinux') }}            # [linux]
  #       - {{ cdt('libselinux-devel') }}      # [linux]
  #       - {{ cdt('libxdamage') }}            # [linux]
  #       - {{ cdt('libxdamage-devel') }}      # [linux]
  #       - {{ cdt('libxfixes') }}             # [linux]
  #       - {{ cdt('libxfixes-devel') }}       # [linux]
  #       - {{ cdt('libxxf86vm') }}            # [linux]
  #       - {{ cdt('libxxf86vm-devel') }}      # [linux]
  #       - {{ cdt('libsm-devel') }}           # [linux]
  #       - {{ cdt('libice-devel') }}          # [linux]
  #       - {{ cdt('libxcb') }}                # [linux]
  #       - {{ cdt('libxcb-devel') }}          # [linux]
  #       - {{ cdt('expat-devel') }}           # [linux]
  #       - {{ cdt('pcre') }}                  # [linux]
  #       - {{ cdt('libglvnd-glx') }}          # [linux]
  #       - {{ cdt('libglvnd-egl') }}          # [linux]
  #       - {{ cdt('libxkbcommon-devel') }}    # [linux]
  #       - {{ cdt('xcb-util-devel') }}        # [linux]
  #       - {{ cdt('xcb-util-image-devel') }}  # [linux]
  #       - {{ cdt('xcb-util-keysyms-devel') }}     # [linux]
  #       - {{ cdt('xcb-util-renderutil-devel') }}  # [linux]
  #       - {{ cdt('xcb-util-wm-devel') }}          # [linux]
  #       - jom                                    # [win]
  #       - python                                 # [build_platform != target_platform]
  #       - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  #       - pyqt-builder                           # [build_platform != target_platform]
  #       - sip                                    # [build_platform != target_platform]
  #       - make
  #     host:
  #       - python
  #       - pip
  #       - sip                                    # [build_platform == target_platform]
  #       - toml
  #       - my-pyqt6-pyqt-builder                           # [build_platform == target_platform]
  #       - packaging
  #       - pyqt6
  #       - qt6-main
  #       # - qt-webengine
  #       - {{ cdt('mesa-libgl-devel') }}          # [linux]
  #       - {{ cdt('mesa-libegl-devel') }}         # [linux]
  #     run:
  #       - python
  #       - {{ pin_subpackage('pyqt6', max_pin='x.x') }}
  #   test:
  #     imports:
  #       - PyQt6.QtWebEngine
  #       - PyQt6.QtWebEngineCore
  #       - PyQt6.QtWebEngineWidgets

  - name: pyqt6-charts
    version: {{ version }}
    script: build-pyqtcharts.sh  # [not win]
    script: bld-pyqtcharts.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage('pyqt6-charts', max_pin='x.x') }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
        - jom                                    # [win]
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        #- pyqt-builder                          # [build_platform != target_platform]
        - my-pyqt6-builder                       # [build_platform != target_platform]
        - sip                                    # [build_platform != target_platform]
        - make
      host:
        - python
        - pip
        - sip                                    # [build_platform == target_platform]
        - toml
        #- pyqt-builder                          # [build_platform == target_platform]
        - my-pyqt6-builder                       # [build_platform == target_platform]
        - packaging
        - qt6-main {{ version }}
        - qt6-charts {{ version }}
        - pyqt6 {{ version }}
        - libgl-devel                        # [linux]
        - libegl-devel                       # [linux]
        - libopengl-devel                    # [linux]
      run:
        - python
        - {{ pin_subpackage('pyqt6', max_pin='x.x') }}
    test:
      imports:
        - PyQt6.QtCharts

about:
  home: https://www.riverbankcomputing.com/software/pyqt/
  license: GPL-3.0-only
  license_family: GPL
  license_file: pyqt/LICENSE
  summary: Python bindings for the Qt cross platform application toolkit
  # The remaining entries in this section are optional, but recommended.
  description: |
    PyQt6 is a comprehensive set of Python bindings for Qt v5.
    It is implemented as more than 35 extension modules and enables Python
    to be used as an alternative application development language to C++ on
    all supported platforms including iOS and Android.
  doc_url: https://www.riverbankcomputing.com/static/Docs/PyQt6/
  dev_url: https://www.riverbankcomputing.com/mailman/listinfo/pyqt/

extra:
  recipe-maintainers:
    - andfoy
    - ccordoba12
    - mingwandroid
    - gillins
    - msarahan
    - ocefpaf
    - jschueller
  feedstock-name: pyqt
