{% set version = "5.15.2" %}
{% set version2 = "5.15" %}

package:
  name: pyqt
  version: {{ version }}

source:
  - url: https://distfiles.macports.org/py-pyqt5/PyQt5-{{ version }}.tar.gz
    sha256: 372b08dc9321d1201e4690182697c5e7ffb2e0770e6b4a45519025134b12e4fc
    patches:
      - 0003-configure.patch
      # remove build path from .bat
      - 0004-configure-winbat.patch  # [win]
      #- py2_segfault.diff
      # - qt5_dll.diff
    folder: pyqt5

  - url: https://www.riverbankcomputing.com/static/Downloads/sip/4.19.25/sip-4.19.25.tar.gz
    sha256: b39d93e937647807bac23579edbff25fe46d16213f708370072574ab1f1b4211
    patches:
      - 0001-Do-not-override-CC-CXX-LINK-in-sipgen-Makefile.patch
      # AttributeError: module 'distutils.sysconfig' has no attribute 'get_config_h_filename'
      - sip-get_config_h_filename.patch
    folder: sip

  - url: https://distfiles.macports.org/py-pyqt5/PyQtWebEngine-{{ version }}.tar.gz
    sha256: 4d72fea774071ce6f76e341a3d2c5d595886c9906a9b9493239c841cce54a634
    folder: pyqtwebengine
    
  - url: https://distfiles.macports.org/py-pyqt5/PyQtChart-{{ version }}.tar.gz
    sha256: 93a6212fb4944d8266ec1f1c10c6e857a06ae6ffb55377ebef58c817b629cbf0
    folder: pyqtcharts

build:
  number: 0
  skip: true  # [win and py27]
  skip: true  # [ppc64le]
  run_exports:
    {{ pin_subpackage('pyqt', max_pin='x.x') }}

requirements:
  run_constrained:                                            # [osx]
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx]
  build:
    # We may want to find and add a Python dbus library?
    # pkg-config --cflags-only-I --libs dbus-1
    # The Python dbus module doesn't seem to be installed.
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxcb') }}                # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('alsa-lib-devel') }}        # [linux]
    - {{ cdt('gtk2-devel') }}            # [linux]
    - {{ cdt('gtkmm24-devel') }}         # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libxcomposite-devel') }}   # [linux]
    - {{ cdt('libxcursor-devel') }}      # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - {{ cdt('libxrandr-devel') }}       # [linux]
    - {{ cdt('pciutils-devel') }}        # [linux]
    - {{ cdt('libxscrnsaver-devel') }}   # [linux]
    - {{ cdt('libxtst-devel') }}         # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - {{ cdt('mesa-libgbm') }}           # [linux]
    - make                               # [linux and aarch64]
    - binutils                           # [linux and aarch64]
    - jom  # [win]
    - pkg-config  # [not win]
    - patch  # [not win]
    - m2-patch  # [win]
    - m2-gcc-libs  # [win]
  host:
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - python
    - dbus  # [not win]
      #- qt 5.15.*
    - qt-main
    - enum34  # [py27]
  run:
    - python
    - {{ pin_compatible("qt-main", max_pin="x.x") }}
    - enum34  # [py27]

test:
  # NOTE: Import tests are done in the run_test.sh because linux-aarch64 requires
  # additional shared objects to be present in the env when the imports are run.
  requires:
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxcb') }}                # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('alsa-lib-devel') }}        # [linux]
    - {{ cdt('gtk2-devel') }}            # [linux]
    - {{ cdt('gtkmm24-devel') }}         # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libxcomposite-devel') }}   # [linux]
    - {{ cdt('libxcursor-devel') }}      # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - {{ cdt('libxrandr-devel') }}       # [linux]
    - {{ cdt('pciutils-devel') }}        # [linux]
    - {{ cdt('libxscrnsaver-devel') }}   # [linux]
    - {{ cdt('libxtst-devel') }}         # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - {{ cdt('mesa-libgbm') }}           # [linux]
  files:
    - pyqt_test.py
    - run_test.sh
  commands:
    - DISPLAY=localhost:1.0 xvfb-run -a bash -c 'python pyqt_test.py'  # [linux and not aarch64]
    - pyuic5 --version  # [not win]

about:
  home: http://www.riverbankcomputing.co.uk/software/pyqt
  license: Commercial, GPL-2.0, GPL-3.0
  license_family: GPL
  license_file: pyqt5/LICENSE
  summary: 'Python binding of the cross-platform GUI toolkit Qt.'
  description: |
    "PyQt is a set of Python v2 and v3 bindings for The Qt Company's Qt
    application framework and runs on all platforms supported by Qt including
    Windows, MacOS/X and Linux. PyQt5 supports Qt v5. PyQt4 supports Qt v4 and
    will build against Qt v5. The bindings are implemented as a set of Python
    modules and contain over 1,000 classes."
  doc_url: https://www.riverbankcomputing.com/software/pyqt/
  dev_url: https://github.com/pyqt

extra:
  recipe-maintainers:
    - ccordoba12
    - mingwandroid
    - gillins
    - msarahan
    - ocefpaf
    - jschueller
