{% set version = "6.7.1" %}
{% set webengine_version = "6.7.0" %}
{% set qt_sip_version = "13.9.1" %}

{% set version_major_minor = ".".join(version.split(".")[:-1]) %}
{% set sip_pkg_name = "PyQt" + version[0] + "-sip" %}

package:
  name: pyqt-split
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/P/PyQt{{ version[0] }}/PyQt{{ version[0] }}-{{ version }}.tar.gz
    sha256: 3672a82ccd3a62e99ab200a13903421e2928e399fda25ced98d140313ad59cb9
    folder: pyqt

  - url: https://pypi.io/packages/source/P/{{ sip_pkg_name }}/{{ sip_pkg_name.replace("-", "_") | lower }}-{{ qt_sip_version }}.tar.gz
    sha256: 15be741d1ae8c82bb7afe9a61f3cf8c50457f7d61229a1c39c24cd6e8f4d86dc
    folder: pyqt_sip

  - url: https://pypi.io/packages/source/P/PyQt{{ version[0] }}-WebEngine/PyQt{{ version[0] }}_WebEngine-{{ webengine_version }}.tar.gz
    sha256: 68edc7adb6d9e275f5de956881e79cca0d71fad439abeaa10d823bff5ac55001
    folder: pyqt_webengine

build:
  number: 0
  skip: True  # [py<38 or s390x]
  skip: True  # [osx and x86_64]

outputs:
  - name: {{ sip_pkg_name | lower }}
    version: {{ qt_sip_version }}
    script: build-pyqt-sip.sh  # [not win]
    script: bld-pyqt-sip.bat   # [win]
    requirements:
      build:
        - {{ compiler('c') }}
      host:
        - python
        - setuptools
        - wheel
        - pip
      run:
        - python
    test:
      imports:
        - PyQt{{ version[0] }}.sip
      requires:
        - pip
      commands:
        - pip check

  - name: pyqt
    version: {{ version }}
    script: build-pyqt.sh  # [not win]
    script: bld-pyqt.bat   # [win]
    build:
      entry_points:
        - pyuic{{ version[0] }} = PyQt{{ version[0] }}.uic.pyuic:main
      run_exports:
        - {{ pin_subpackage('pyqt', max_pin='x.x') }}
      missing_dso_whitelist:
        - $RPATH/libm.so.6
        - $RPATH/libpthread.so.0
        - $RPATH/libc.so.6
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
        - {{ cdt('libx11-devel') }}          # [linux]
        - {{ cdt('libxext-devel') }}         # [linux]
        - {{ cdt('libxrender-devel') }}      # [linux]
        - {{ cdt('mesa-libgl-devel') }}      # [linux]
        - {{ cdt('mesa-libgbm') }}           # [linux]
        - {{ cdt('mesa-libegl-devel') }}     # [linux]
        - {{ cdt('mesa-dri-drivers') }}      # [linux]
        - {{ cdt('libxau-devel') }}          # [linux]
        - {{ cdt('alsa-lib-devel') }}        # [linux]
        - {{ cdt('gtk2-devel') }}            # [linux]
        - {{ cdt('gtkmm24-devel') }}         # [linux]
        - {{ cdt('libdrm-devel') }}          # [linux]
        - {{ cdt('libxcomposite-devel') }}   # [linux]
        - {{ cdt('libxcursor-devel') }}      # [linux]
        - {{ cdt('libxi-devel') }}           # [linux]
        - {{ cdt('libxrandr-devel') }}       # [linux]
        - {{ cdt('pciutils-devel') }}        # [linux]
        - {{ cdt('libxscrnsaver-devel') }}   # [linux]
        - {{ cdt('libxtst-devel') }}         # [linux]
        - {{ cdt('libselinux-devel') }}      # [linux]
        - {{ cdt('libxdamage-devel') }}      # [linux]
        - {{ cdt('libxfixes-devel') }}       # [linux]
        - {{ cdt('libxxf86vm-devel') }}      # [linux]
        - {{ cdt('libsm-devel') }}           # [linux]
        - {{ cdt('libice-devel') }}          # [linux]
        - {{ cdt('libxcb') }}                # [linux]
        - {{ cdt('expat-devel') }}           # [linux and x86_64]
        - {{ cdt('pcre') }}                  # [linux and aarch64]
        - {{ cdt('libglvnd-devel') }}        # [linux and aarch64]
        - jom                                # [win]
        - make                               # [not win]
        - pkg-config
      host:
        - python
        - pyqt-builder >=1.15,<2
        - sip >=6.8.6,<7
        - qtbase {{ version_major_minor }}
        - qtdeclarative {{ version_major_minor }}
        - qtsvg {{ version_major_minor }}
        - qttools {{ version_major_minor }}
        - qtwebchannel {{ version_major_minor }}
        - qtwebsockets {{ version_major_minor }}
      run:
        - python
        - {{ pin_subpackage(sip_pkg_name | lower, exact=True) }}
    test:
      files:
        - pyqt_test.py
      imports:
        - PyQt{{ version[0] }}
      requires:
        - pip
        - {{ cdt('xorg-x11-proto-devel') }}        # [linux]
        - {{ cdt('libx11-devel') }}                # [linux]
        - {{ cdt('libxext') }}               # [linux]
        - {{ cdt('libxrender') }}            # [linux]
        - {{ cdt('mesa-libgl') }}            # [linux]
        - {{ cdt('mesa-libgbm') }}           # [linux]
        - {{ cdt('mesa-libegl') }}           # [linux]
        - {{ cdt('mesa-dri-drivers') }}      # [linux]
        - {{ cdt('libxau') }}                # [linux]
        - {{ cdt('alsa-lib') }}              # [linux]
        - {{ cdt('gtk2') }}                  # [linux]
        - {{ cdt('gtkmm24') }}               # [linux]
        - {{ cdt('libdrm') }}                # [linux]
        - {{ cdt('libxcomposite') }}         # [linux]
        - {{ cdt('libxcursor') }}            # [linux]
        - {{ cdt('libxi') }}                 # [linux]
        - {{ cdt('libxrandr') }}             # [linux]
        - {{ cdt('pciutils-devel') }}        # [linux]
        - {{ cdt('libxscrnsaver') }}         # [linux]
        - {{ cdt('libxtst') }}               # [linux]
        - {{ cdt('libselinux') }}            # [linux]
        - {{ cdt('libxdamage') }}            # [linux]
        - {{ cdt('libxfixes') }}             # [linux]
        - {{ cdt('libxxf86vm') }}            # [linux]
        - {{ cdt('libsm') }}                 # [linux]
        - {{ cdt('libice') }}                # [linux]
        - {{ cdt('libxcb') }}                # [linux]
        - {{ cdt('expat') }}                 # [linux and x86_64]
        - {{ cdt('pcre') }}                  # [linux and aarch64]
        - {{ cdt('libglvnd') }}              # [linux and aarch64]
      commands:
        - pip check

  - name: pyqtwebengine
    version: {{ webengine_version }}
    script: build-pyqtwebengine.sh  # [not win]
    script: bld-pyqtwebengine.bat   # [win]
    build:
      run_exports:
        - {{ pin_subpackage('pyqtwebengine', max_pin='x.x') }}
      missing_dso_whitelist:
        - $RPATH/libm.so.6
        - $RPATH/libpthread.so.0
        - $RPATH/libc.so.6
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
        - {{ cdt('libx11-devel') }}          # [linux]
        - {{ cdt('libxext-devel') }}         # [linux]
        - {{ cdt('libxrender-devel') }}      # [linux]
        - {{ cdt('mesa-libgl-devel') }}      # [linux]
        - {{ cdt('mesa-libegl-devel') }}     # [linux]
        - {{ cdt('mesa-dri-drivers') }}      # [linux]
        - {{ cdt('libxau-devel') }}          # [linux]
        - {{ cdt('alsa-lib-devel') }}        # [linux]
        - {{ cdt('gtk2-devel') }}            # [linux]
        - {{ cdt('gtkmm24-devel') }}         # [linux]
        - {{ cdt('libdrm-devel') }}          # [linux]
        - {{ cdt('libxcomposite-devel') }}   # [linux]
        - {{ cdt('libxcursor-devel') }}      # [linux]
        - {{ cdt('libxi-devel') }}           # [linux]
        - {{ cdt('libxrandr-devel') }}       # [linux]
        - {{ cdt('pciutils-devel') }}        # [linux]
        - {{ cdt('libxscrnsaver-devel') }}   # [linux]
        - {{ cdt('libxtst-devel') }}         # [linux]
        - {{ cdt('libselinux-devel') }}      # [linux]
        - {{ cdt('libxdamage-devel') }}      # [linux]
        - {{ cdt('libxfixes-devel') }}       # [linux]
        - {{ cdt('libxxf86vm-devel') }}      # [linux]
        - {{ cdt('libsm-devel') }}           # [linux]
        - {{ cdt('libice-devel') }}          # [linux]
        - {{ cdt('libxcb') }}                # [linux]
        - {{ cdt('expat-devel') }}           # [linux and x86_64]
        - {{ cdt('pcre') }}                  # [linux and aarch64]
        - {{ cdt('libglvnd-devel') }}        # [linux and aarch64]
        - jom                                # [win]
        - make                               # [not win]
        - pkg-config
      host:
        - python
        - pyqt-builder >=1.15,<2
        - sip >=6.8.6,<7
        - {{ pin_subpackage('pyqt', exact=True) }}
        - qtbase {{ version_major_minor }}
        - qtdeclarative {{ version_major_minor }}
        - qtwebchannel {{ version_major_minor }}
        - qtwebengine {{ version_major_minor }}
      run:
        - python
        - {{ pin_subpackage('pyqt', max_pin='x.x') }}
    test:
      imports:
        - PyQt{{ version[0] }}
      requires:
        - pip
        - {{ cdt('xorg-x11-proto-devel') }}    # [linux]
        - {{ cdt('libx11-devel') }}            # [linux]
        - {{ cdt('libxext') }}           # [linux]
        - {{ cdt('libxrender') }}        # [linux]
        - {{ cdt('mesa-libgl') }}        # [linux]
        - {{ cdt('mesa-libegl') }}       # [linux]
        - {{ cdt('mesa-dri-drivers') }}  # [linux]
        - {{ cdt('libxau') }}            # [linux]
        - {{ cdt('alsa-lib') }}          # [linux]
        - {{ cdt('gtk2') }}              # [linux]
        - {{ cdt('gtkmm24') }}           # [linux]
        - {{ cdt('libdrm') }}            # [linux]
        - {{ cdt('libxcomposite') }}     # [linux]
        - {{ cdt('libxcursor') }}        # [linux]
        - {{ cdt('libxi') }}             # [linux]
        - {{ cdt('libxrandr') }}         # [linux]
        - {{ cdt('pciutils-devel') }}    # [linux]
        - {{ cdt('libxscrnsaver') }}     # [linux]
        - {{ cdt('libxtst') }}           # [linux]
        - {{ cdt('libselinux') }}        # [linux]
        - {{ cdt('libxdamage') }}        # [linux]
        - {{ cdt('libxfixes') }}         # [linux]
        - {{ cdt('libxxf86vm') }}        # [linux]
        - {{ cdt('libsm') }}             # [linux]
        - {{ cdt('libice') }}            # [linux]
        - {{ cdt('libxcb') }}            # [linux]
        - {{ cdt('expat') }}             # [linux and x86_64]
        - {{ cdt('pcre') }}              # [linux and aarch64]
        - {{ cdt('libglvnd') }}          # [linux and aarch64]
      commands:
        - pip check

about:
  home: https://www.riverbankcomputing.com/software/pyqt/
  license: GPL-3.0-only
  license_family: GPL
  license_file: pyqt/LICENSE
  summary: Python bindings for the Qt cross platform application toolkit
  description: |
    PyQt{{ version[0] }} is a comprehensive set of Python bindings for Qt v{{ version[0] }}.
    It is implemented as more than 35 extension modules and enables Python
    to be used as an alternative application development language to C++ on
    all supported platforms including iOS and Android.
  doc_url: https://www.riverbankcomputing.com/static/Docs/PyQt{{ version[0] }}/
  dev_url: https://www.riverbankcomputing.com/mailman/listinfo/pyqt/

extra:
  skip-lints:
    - missing_wheel
    - missing_python_build_tool
    - host_section_needs_exact_pinnings
  recipe-maintainers:
    - andfoy
    - ccordoba12
    - katietz
    - mingwandroid
    - gillins
    - msarahan
    - ocefpaf
    - jschueller
  feedstock-name: pyqt
