{% set version = "5.6.0" %}

package:
  name: pyqt
  version: {{ version }}

source:
  fn:   PyQt5_gpl-5.6.zip  # [win]
  url:  http://sourceforge.net/projects/pyqt/files/PyQt5/PyQt-5.6/PyQt5_gpl-5.6.zip  # [win]
  sha1: 63a03d0f6e7f6e2e9dc90311020fbb2a2edc8cf0  # [win]
  fn:   PyQt5_gpl-5.6.tar.gz  # [not win]
  url:  http://sourceforge.net/projects/pyqt/files/PyQt5/PyQt-5.6/PyQt5_gpl-5.6.tar.gz  # [not win]
  sha1: 8920e4094470ff93f79e257c37c46f5cd0bff7ab  # [not win]
  patches:
    - configure_python_library.patch

build:
  number: 1009

requirements:
  build:
    - jom  # [win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    # The CDT packages below are those used in qt-feedstock
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxfixes') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
  host:
    - python
    - qt
    - sip 4.18
  run:
    - python
    - qt
    - sip 4.18

test:
  files:
    - pyqt_test.py
  imports:
    - PyQt5.QtCore
    - PyQt5.QtGui
    - PyQt5.QtHelp
    - PyQt5.QtMultimedia
    - PyQt5.QtMultimediaWidgets
    - PyQt5.QtNetwork
    - PyQt5.QtOpenGL
    - PyQt5.QtPrintSupport
    - PyQt5.QtQml
    - PyQt5.QtQuick
    - PyQt5.QtSvg
    - PyQt5.QtTest
    - PyQt5.QtWebChannel
    - PyQt5.QtWebKitWidgets
    - PyQt5.QtWebSockets
    - PyQt5.QtWidgets
    - PyQt5.QtXml
    - PyQt5.QtXmlPatterns
  commands:
    - DISPLAY=localhost:1.0 xvfb-run -a bash -c 'python pyqt_test.py'  # [linux]

about:
  home: http://www.riverbankcomputing.co.uk/software/pyqt
  license: Commercial, GPL-2.0, GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: 'Python binding of the cross-platform GUI toolkit Qt.'
  description: |
    "PyQt is a set of Python v2 and v3 bindings for The Qt Company's Qt
    application framework and runs on all platforms supported by Qt including
    Windows, MacOS/X and Linux. PyQt5 supports Qt v5. PyQt4 supports Qt v4 and
    will build against Qt v5. The bindings are implemented as a set of Python
    modules and contain over 1,000 classes."
  doc_url: https://www.riverbankcomputing.com/software/pyqt/
  dev_url: https://github.com/pyqt

extra:
  recipe-maintainers:
    - ccordoba12
    - mingwandroid
    - gillins
    - msarahan
    - ocefpaf
    - jschueller
