appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: kVZKNpNuS6dw8lVVWEBAnA9ev7Noyy06QM1iMKwSDKQEhIak9SLj1PfIm5g0a+SEJHBnNX3qjlFzv4T53Appko0Ca/wvEnt/I6gIfNcZMwODEY7NHh6wIAfTvJVKAAJdeMouebJMko37kdMY0OZb9zz2F/jD7IdVVYLJs0eSXaFQv5L5FhSA1YlmtW0iijdXOab6FPtpAyGsSJGU9wl/Th0EXoOO3Wr7HDzPRfB6eRP0tDIsuaCw6R2j6XEqKjQU73M7+LI9gHy28njYOmfIMqA11a3NvdqrfhQE4EkkbG0saDmYOofapegeqonwuiA9KIa65OpovU/yNNp83CPI5JVdYVtn3zeIhzdFX0KTa95zG8ie16SUwhxPEGkZCqGKJdQ0cpliHKMlc3vD+4xFMNfTXyOxm+jXzMs8DjfYhahbjzTFztmBq/tGz4L9s90gjHe2qHzC3kdl7xgf15NQkCQHlsk9A+dKOKNz+Gutl5KIqqxkttLVJvIWIF1Jg2NGZ9kh+b56TUDaJevcipFOVQZTUL2EQcpx2DKLxiOCjU8hl1reTL3V9UnUBO/CMiGeh+r1cA+8/l8RRUutkoamg5tIpVIVm1ETfkUS6g4JugW+Bmcg5sZQ/DyiEAVuHUl9db8OmoxSMYSqQ6JSQyhiBP9rIlOLyjoymlKCTSsaVlQ=}
